name: Build binarys

on:
  push:
    branches: [main]
    paths: [pdfGenerator/**]
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --quiet -y libpq-dev libglfw3 libglfw3-dev libfreetype6-dev libssl-dev libsqlite3-dev valgrind gcc-mingw-w64-x86-64
    - name: Setup Vlang
        uses: vlang/setup-v@v1.1
        with:
          check-latest: true
          stable: true
          architecture: 'linux'
    - name: Build
      working-directory: pdfGenerator
      run: |
        ${{ v-bin-path }} ./main.v -os linux -o renderpdf
        ${{ v-bin-path }} ../main.v -os windows -o renderpdf.exe
        ls